export type RoyalDecreeSection = {
  body: string[];
  heading: string;
  items?: string[];
};

export type RoyalDecree = {
  href: string;
  icon: string;
  sections: RoyalDecreeSection[];
  slug: string;
  summary: string;
  title: string;
};

export type PaymentBrandAsset = {
  alt: string;
  className: string;
  label: string;
  src: string;
};

export const paymentBrandAssets: PaymentBrandAsset[] = [
  {
    alt: "Visa",
    className: "h-6 w-auto object-contain sm:h-7",
    label: "Visa",
    src: "/brand/payment/visa.svg",
  },
  {
    alt: "Verified by Visa",
    className: "h-6 w-auto object-contain sm:h-7",
    label: "Verified by Visa",
    src: "/brand/payment/verified-by-visa.png",
  },
  {
    alt: "Mastercard",
    className: "h-6 w-auto object-contain sm:h-7",
    label: "Mastercard",
    src: "/brand/payment/mastercard.svg",
  },
  {
    alt: "Mastercard SecureCode",
    className: "h-6 w-auto object-contain sm:h-7",
    label: "Mastercard SecureCode",
    src: "/brand/payment/mastercard-securecode.png",
  },
  {
    alt: "Apple Pay",
    className: "h-6 w-auto object-contain sm:h-7",
    label: "Apple Pay",
    src: "/brand/payment/apple-pay.svg",
  },
  {
    alt: "Samsung Pay",
    className: "h-[1.15rem] w-auto object-contain sm:h-[1.35rem]",
    label: "Samsung Pay",
    src: "/brand/payment/samsung-pay.svg",
  },
  {
    alt: "PayFast by Network",
    className: "h-[2.25rem] w-auto object-contain sm:h-[2.625rem]",
    label: "PayFast by Network",
    src: "/brand/payment/payfast-by-network.svg",
  },
];

export const paymentBrandDisclosure =
  "Online payments are processed securely by PayFast by Network with supported Visa, Mastercard, Apple Pay, Samsung Pay, Verified by Visa and Mastercard SecureCode flows.";

export const royalDecrees: RoyalDecree[] = [
  {
    href: "/royal-decrees/terms-and-conditions",
    icon: "📜",
    sections: [
      {
        heading: "Definitions",
        body: [
          "\"The Royal Countess\", \"we\", \"us\" and \"our\" refer to The Royal Countess by Zingara and Zingara Productions (Pty) Ltd, the operator of this booking platform.",
          "\"Guest\" means any person using the platform, making a booking, attending an event or receiving a ticket. \"Platform\" means this website, booking system, digital ticketing experience and related communications.",
        ],
      },
      {
        heading: "Acceptance",
        body: [
          "By using the platform, creating a booking, submitting an enquiry, making payment or attending an experience, guests agree to these Terms & Conditions and the related Royal Decrees displayed on this site.",
          "If a guest does not agree with these terms, they should not continue with the booking or payment process.",
        ],
      },
      {
        heading: "Eligibility And Accurate Information",
        body: [
          "Guests must provide accurate names, contact details, guest numbers, dietary notes and any special requirements. The Royal Countess may rely on the information supplied to prepare seating, tickets, communication and operational service.",
          "Guests must be legally able to enter into the transaction and must use the platform lawfully and respectfully.",
        ],
      },
      {
        heading: "Electronic Communications",
        body: [
          "Guests consent to receiving booking-related electronic communications, including confirmations, payment notices, tickets, reminders, table updates and service messages.",
          "Electronic records generated by the platform may be used to confirm booking status, payment status, communication history and ticket activity.",
          "This electronic contracting and communication process is intended to align with the Electronic Communications and Transactions Act, 2002 (ECTA).",
        ],
      },
      {
        heading: "Intellectual Property",
        body: [
          "All branding, artwork, design, copy, images, venue concepts, ticket design and platform content remain the property of The Royal Countess by Zingara or its licensors.",
          "Guests may not copy, reproduce, adapt or commercially use platform content without written permission.",
        ],
      },
      {
        heading: "Liability",
        body: [
          "The Royal Countess takes reasonable care to provide a secure, accurate and reliable booking experience. However, the platform may occasionally be affected by internet service issues, payment provider availability, browser behaviour or operational interruptions.",
          "To the fullest extent allowed by law, The Royal Countess is not liable for indirect loss, loss of opportunity, technical interruption or guest-side errors, except where liability cannot legally be excluded.",
        ],
      },
      {
        heading: "Indemnity",
        body: [
          "Guests agree to indemnify The Royal Countess against loss, damage, claims or costs caused by unlawful use of the platform, inaccurate information, misuse of tickets, breach of these terms or conduct that affects other guests or the venue.",
        ],
      },
      {
        heading: "Force Majeure",
        body: [
          "The Royal Countess will not be responsible for failure or delay caused by events beyond reasonable control, including severe weather, power failure, venue emergency, acts of government, public disorder, supplier failure, network disruption, payment provider outage or other unavoidable events.",
        ],
      },
      {
        heading: "Governing Law And Disputes",
        body: [
          "These terms are governed by the laws of the Republic of South Africa.",
          "Guests are encouraged to contact Guest Services first so that concerns can be resolved promptly and professionally. If a dispute cannot be resolved informally, it may be handled through the appropriate South African legal or consumer protection process.",
        ],
      },
      {
        heading: "Severability, Entire Agreement And Amendments",
        body: [
          "If any part of these terms is found to be invalid or unenforceable, the remaining terms continue to apply.",
          "These Terms & Conditions, together with the related Royal Decrees, form the agreement that governs use of the platform and guest bookings. The Royal Countess may update these terms when operational, legal or payment requirements change.",
        ],
      },
    ],
    slug: "terms-and-conditions",
    summary:
      "The general terms for using The Royal Countess by Zingara booking platform.",
    title: "Terms & Conditions",
  },
  {
    href: "/royal-decrees/booking-terms",
    icon: "🎟",
    sections: [
      {
        heading: "Creating A Booking",
        body: [
          "Bookings are created through the public booking journey or through an approved corporate workflow. Guests should review the event date, time, venue, seating zone, guest count and contact details before continuing.",
          "A booking may remain pending until payment is successfully confirmed and the platform issues the relevant confirmation or ticket.",
        ],
      },
      {
        heading: "Digital Ticket Delivery",
        body: [
          "Tickets are delivered digitally immediately after successful payment confirmation.",
          "Delivery methods include email, live digital ticket access and PDF download. Guests should ensure that the email address and mobile number supplied during booking are correct.",
        ],
        items: [
          "Delivery method: Email",
          "Delivery method: Live Digital Ticket",
          "Delivery method: PDF Download",
          "Delivery timing: Immediately after successful payment",
        ],
      },
      {
        heading: "Seating Allocation",
        body: [
          "The platform may suggest a best-fit table or seating zone based on availability, party size and venue rules. Final seating remains subject to operational requirements, venue layout, table availability and any confirmed table changes.",
          "Guests should contact Guest Services promptly if accessibility, mobility, dietary or special seating considerations apply.",
        ],
      },
      {
        heading: "Venue Rules And Guest Responsibilities",
        body: [
          "Guests are expected to arrive with a valid ticket or booking reference, respect venue staff, follow venue instructions and avoid conduct that disrupts the experience for others.",
          "The Royal Countess may refuse admission or remove a guest where behaviour, safety or ticket validity requires it, subject to applicable law.",
        ],
      },
      {
        heading: "Late Arrivals",
        body: [
          "Late arrivals may affect seating, service timing and access to parts of the performance. Guests should arrive at the time communicated with their booking or ticket.",
          "The venue team will assist where possible, but late seating is not guaranteed if it would disrupt the experience.",
        ],
      },
      {
        heading: "Accessibility",
        body: [
          "Guests with accessibility requirements should notify The Royal Countess as early as possible. The team will make reasonable efforts to assist, subject to venue constraints and availability.",
        ],
      },
    ],
    slug: "booking-terms",
    summary:
      "Booking-specific terms covering reservations, seating, tickets, delivery and venue entry.",
    title: "Booking Terms",
  },
  {
    href: "/royal-decrees/booking-and-cancellation-policy",
    icon: "↩",
    sections: [
      {
        heading: "Booking Changes",
        body: [
          "Guests who need to change a booking should contact Guest Services with the booking reference, requested change and reason for the request.",
          "Changes are subject to availability, booking type, payment status, seating availability and operational preparation already completed for the event.",
        ],
      },
      {
        heading: "Cancellation Requests",
        body: [
          "Cancellation requests must be submitted to Guest Services as soon as possible. The Royal Countess will review the booking date, payment status, cancellation reason and operational impact before confirming the available options.",
          "Corporate bookings may require additional review because quotations, invoices, guest numbers, menus and supplier arrangements may already have been prepared.",
        ],
      },
      {
        heading: "Refund Review",
        body: [
          "Refund eligibility depends on the timing of the cancellation request, the nature of the booking, the payment status and any event-specific terms agreed with the guest or company.",
          "Approved refunds are processed through the appropriate payment channel where possible. Bank and payment provider processing times may apply.",
          "Requests are reviewed with reference to the Consumer Protection Act, 2008 (CPA), the nature of the hospitality service and the operational preparation already undertaken for the event.",
        ],
      },
      {
        heading: "No Automatic Cancellation Through Return Or Cancel Pages",
        body: [
          "Returning from a payment provider or visiting a cancellation page does not by itself cancel or refund a booking.",
          "The booking status reflected in the platform and confirmed by The Royal Countess team is the operational source of truth.",
        ],
      },
      {
        heading: "Event Changes By The Royal Countess",
        body: [
          "If The Royal Countess must postpone, reschedule or cancel an event, affected guests will be contacted using the details supplied with the booking.",
          "The team will explain the available options clearly and in line with applicable consumer protection requirements.",
        ],
      },
    ],
    slug: "booking-and-cancellation-policy",
    summary:
      "The policy for booking changes, cancellations, refund review and event changes.",
    title: "Booking & Cancellation Policy",
  },
  {
    href: "/royal-decrees/payment-terms",
    icon: "💳",
    sections: [
      {
        heading: "Transaction Currency",
        body: [
          "All prices, deposits, balances and payments are displayed and processed in South African Rand (ZAR), unless expressly stated otherwise by The Royal Countess.",
        ],
      },
      {
        heading: "Accepted Payment Methods",
        body: [
          "Online payments are processed through PayFast by Network. Accepted payment methods include Visa, Mastercard, Apple Pay and Samsung Pay where available through PayFast.",
          "Card authentication may include Verified by Visa and Mastercard SecureCode where required.",
          "All online transactions are processed in South African Rand (ZAR).",
        ],
        items: [
          "Visa",
          "Mastercard",
          "Apple Pay",
          "Samsung Pay",
          "Verified by Visa",
          "Mastercard SecureCode",
          "PayFast by Network",
        ],
      },
      {
        heading: "Payment Security",
        body: [
          "The Royal Countess does not collect or store card numbers on this platform. Card and payment details are processed by PayFast through its secure hosted payment environment.",
          "PayFast payment processing may include PCI DSS-aligned controls, 3D Secure, Verified by Visa, Mastercard SecureCode and fraud prevention tools.",
        ],
      },
      {
        heading: "Deposits And Pending Payments",
        body: [
          "Where a deposit option is offered, the payment summary will show the amount due today and any balance that remains payable.",
          "A booking may remain pending until successful payment confirmation is received. Tickets are not issued merely because a guest started checkout.",
        ],
      },
      {
        heading: "Duplicate Payments And Chargebacks",
        body: [
          "Guests who believe they have made a duplicate payment should contact Guest Services with the booking reference and payment details so the matter can be reviewed.",
          "Chargebacks, reversals and disputed payments may affect booking status, ticket validity and entry until the matter is resolved.",
        ],
      },
      {
        heading: "Payment Confirmation",
        body: [
          "Payment confirmation is based on verified payment notification and the booking record. Returning from PayFast to the platform does not by itself confirm payment.",
          "Once payment is successfully confirmed, the platform may issue tickets, update payment status and send the relevant confirmation communication.",
        ],
      },
    ],
    slug: "payment-terms",
    summary:
      "Payment terms covering ZAR transactions, PayFast processing, deposits, security and confirmation.",
    title: "Payment Terms",
  },
  {
    href: "/royal-decrees/privacy-policy",
    icon: "🔒",
    sections: [
      {
        heading: "Lawful Basis For Processing",
        body: [
          "The Royal Countess processes personal information to create and manage bookings, deliver tickets, communicate with guests, provide venue services, meet legal obligations and protect legitimate business and security interests.",
          "Processing is carried out in line with the Protection of Personal Information Act, 2013 (POPIA), and related South African privacy requirements.",
        ],
      },
      {
        heading: "Personal Information Collected",
        body: [
          "Information may include names, email addresses, mobile numbers, booking references, guest counts, seating information, dietary notes, accessibility requests, payment status, ticket activity and communication history.",
          "Corporate enquiries may include company details, event requirements, bar tab selections, add-ons, location acknowledgement and operational notes.",
        ],
      },
      {
        heading: "Purpose Of Processing",
        body: [
          "Personal information is used to manage bookings, process payments, issue digital tickets, support check-in, send service communications, respond to enquiries, manage corporate requests and keep accurate operational records.",
          "The Royal Countess may also process limited staff information for admin access, role management and platform security.",
        ],
      },
      {
        heading: "Data Processors",
        body: [
          "The Royal Countess may use trusted service providers for hosting, database storage, authentication, payment processing, email delivery, push notifications and platform operations.",
          "These providers may process information only as required to provide their services and support the guest experience.",
        ],
      },
      {
        heading: "Data Retention",
        body: [
          "Booking, payment, ticket and communication records are retained for as long as reasonably needed for guest service, accounting, legal, security, operational and reporting purposes.",
          "Where information is no longer required, The Royal Countess will take reasonable steps to delete, anonymise or restrict it according to operational and legal requirements.",
        ],
      },
      {
        heading: "Data Subject Rights",
        body: [
          "Guests may request access to, correction of or deletion of their personal information, subject to legal and operational limitations.",
          "Requests should be directed to Guest Services using the contact details published in the Contact & Company Information decree.",
        ],
      },
      {
        heading: "Information Regulator And POPIA Complaints",
        body: [
          "Guests may contact The Royal Countess first so that privacy concerns can be reviewed and resolved.",
          "If a guest remains dissatisfied, they may lodge a complaint with the Information Regulator of South Africa using the official channels published by the Regulator.",
        ],
      },
      {
        heading: "Security Safeguards",
        body: [
          "The Royal Countess uses reasonable technical and organisational safeguards to protect personal information, including secure hosting, controlled staff access, encrypted transport where available and role-based operational access.",
        ],
      },
    ],
    slug: "privacy-policy",
    summary:
      "How guest, booking, staff and communication information is handled under POPIA.",
    title: "Privacy Policy",
  },
  {
    href: "/royal-decrees/cookie-policy",
    icon: "🍪",
    sections: [
      {
        heading: "Purpose",
        body: [
          "This Cookie Policy explains how The Royal Countess platform uses cookies and browser storage to support secure access, preferences and a smooth guest experience.",
          "It should be read together with the Privacy Policy.",
        ],
      },
      {
        heading: "Essential Cookies",
        body: [
          "Essential cookies may be used for private preview access, authentication, session handling, security and the correct operation of the platform.",
          "Without essential cookies, some areas of the booking platform, admin area or password gate may not work correctly.",
        ],
      },
      {
        heading: "Preference Storage",
        body: [
          "Browser storage may be used for selected location, notification preferences, Academy progress, favourites and recently viewed lessons.",
          "These preferences improve convenience and do not replace official booking, ticket or payment records.",
        ],
      },
      {
        heading: "Managing Cookies",
        body: [
          "Guests can manage cookies through their browser settings. Blocking or deleting cookies may require a guest to repeat certain steps or sign in again.",
        ],
      },
      {
        heading: "Future Analytics Or Marketing Cookies",
        body: [
          "If additional analytics or marketing tools are introduced, this Cookie Policy and the Privacy Policy should be reviewed before those tools are used.",
        ],
      },
    ],
    slug: "cookie-policy",
    summary:
      "How cookies and local browser storage support the Zingara platform.",
    title: "Cookie Policy",
  },
  {
    href: "/royal-decrees/access-to-information-paia",
    icon: "📂",
    sections: [
      {
        heading: "Purpose Of The PAIA Decree",
        body: [
          "This page provides access-to-information guidance for requests made to Zingara Productions (Pty) Ltd under the Promotion of Access to Information Act, 2000 (PAIA).",
          "It also acknowledges that certain requests may involve personal information protected by POPIA.",
        ],
      },
      {
        heading: "Information Officer",
        body: [
          "The Information Officer for PAIA-related requests is Guest Services.",
        ],
        items: ["Email: boxoffice@zingara.co.za"],
      },
      {
        heading: "Records And Categories",
        body: [
          "Records may include company information, booking records, customer service records, operational documents, payment references, supplier records and other records held by the company.",
          "Access may be refused or limited where records are confidential, privileged, commercially sensitive, not held by the company or protected by law.",
        ],
      },
      {
        heading: "Request Process",
        body: [
          "A requester should identify the record requested, provide contact details, explain the right they wish to exercise or protect where required, and provide enough detail for the company to locate the record.",
          "The Royal Countess may request proof of identity or authority before releasing records.",
        ],
      },
      {
        heading: "Fees And Timeframes",
        body: [
          "Any applicable request fees, access fees, timeframes or procedural requirements will be communicated after the request has been reviewed.",
        ],
      },
    ],
    slug: "access-to-information-paia",
    summary:
      "Access-to-information guidance for PAIA requests and official records.",
    title: "Access to Information (PAIA)",
  },
  {
    href: "/royal-decrees/security",
    icon: "🛡",
    sections: [
      {
        heading: "Secure Browsing",
        body: [
          "The Royal Countess booking platform is served over HTTPS so that information submitted through the website is protected in transit where supported by the guest’s browser and network.",
        ],
      },
      {
        heading: "Secure Payment Processing",
        body: [
          "Online payments are processed through PayFast by Network. Guests are redirected to a secure PayFast payment environment when completing online payment.",
          "The Royal Countess platform does not collect or store full card numbers.",
        ],
      },
      {
        heading: "PCI DSS And 3D Secure",
        body: [
          "Card processing is handled by PayFast within its hosted payment environment. PayFast payment flows may use PCI DSS-aligned controls and 3D Secure authentication such as Verified by Visa and Mastercard SecureCode.",
        ],
      },
      {
        heading: "Fraud Prevention",
        body: [
          "The platform uses booking references, verified payment notifications, digital ticket records and ticket validation to reduce fraud and duplicate entry risk.",
          "The Royal Countess may review or hold a booking where payment, ticket or guest details appear unusual or require confirmation.",
        ],
      },
      {
        heading: "Customer Payment Security",
        body: [
          "Guests should complete payment only through the official booking platform or an approved payment link. The Royal Countess will never ask guests to send full card details by email, messaging app or telephone.",
        ],
      },
    ],
    slug: "security",
    summary:
      "Security information covering HTTPS, PayFast, PCI DSS, 3D Secure and guest payment safety.",
    title: "Security",
  },
  {
    href: "/royal-decrees/contact-and-company-information",
    icon: "📞",
    sections: [
      {
        heading: "Trading Name",
        body: ["The Royal Countess by Zingara"],
      },
      {
        heading: "Registered Company",
        body: ["Zingara Productions (Pty) Ltd"],
        items: [
          "Registration Number: 2025/603851/07",
          "VAT Number: 4450323193",
          "Country of Domicile: South Africa",
        ],
      },
      {
        heading: "Registered Address",
        body: [
          "22 Tiverton Road\nPlumstead\nCape Town\nWestern Cape\n7800\nSouth Africa",
        ],
      },
      {
        heading: "Guest Services",
        body: ["Email: boxoffice@zingara.co.za", "Telephone: 021 891 0448"],
      },
      {
        heading: "Bookings",
        body: [
          "Bookings: bookings@zingara.co.za",
          "Corporate Bookings: corporatebookings@zingara.co.za",
        ],
      },
      {
        heading: "Business Hours",
        body: ["Monday – Friday\n08:00 – 17:00"],
      },
      {
        heading: "Information Officer",
        body: ["Guest Services\nboxoffice@zingara.co.za"],
      },
    ],
    slug: "contact-and-company-information",
    summary:
      "Official guest services, booking, company and information officer details.",
    title: "Contact & Company Information",
  },
];

export function getRoyalDecree(slug: string) {
  return royalDecrees.find((decree) => decree.slug === slug) ?? null;
}
