import type { PublicReviewRecord } from "@/lib/reviews/reviews";

const longReview =
  "From the moment we arrived, the entire evening felt considered and beautifully produced. " +
  "The performances, service, music and atmosphere worked together effortlessly, and every member of our group left with a favourite moment to talk about. ".repeat(5);

export const wixPreviewReviews: PublicReviewRecord[] = [
  {
    featured: true,
    id: "3a034a63-72dd-42d7-b19b-f9474aa68e93",
    publicDisplayName: "Chanel D.",
    publicationConsent: true,
    publishedAt: "2026-10-01T15:20:00.000Z",
    rating: 5,
    reviewText: "The show was absolutely incredible and the service made the whole evening feel special.",
    status: "published",
    venue: "johannesburg",
    verifiedGuest: true,
  },
  {
    featured: true,
    id: "5ec734c6-6a3a-42ec-bc75-dbd58ed25ed4",
    publicDisplayName: "Lerato M.",
    publicationConsent: true,
    publishedAt: "2026-09-30T18:40:00.000Z",
    rating: 4,
    reviewText: "A polished, joyful night with memorable performances and wonderfully attentive staff.",
    status: "published",
    venue: "cape-town",
    verifiedGuest: true,
  },
  {
    featured: false,
    id: "64dd9acf-b680-42ab-8bb3-802d0caec52c",
    publicDisplayName: "Noah P.",
    publicationConsent: true,
    publishedAt: "2026-09-29T12:00:00.000Z",
    rating: 1,
    reviewText: "The team listened carefully to our concerns and followed up with us after the performance.",
    status: "published",
    venue: "johannesburg",
    verifiedGuest: true,
  },
  {
    featured: false,
    id: "9856c185-f07d-49ac-b68f-7b6a4e18ccf9",
    publicDisplayName: "Priya S.",
    publicationConsent: true,
    publishedAt: "2026-09-28T17:15:00.000Z",
    rating: 5,
    reviewText: longReview,
    status: "published",
    venue: "cape-town",
    verifiedGuest: true,
  },
  {
    featured: false,
    id: "2836689c-5c1b-4f85-9f4d-8620d8dd8fe1",
    publicDisplayName: "Private Guest",
    publicationConsent: false,
    publishedAt: "2026-09-27T15:00:00.000Z",
    rating: 5,
    reviewText: "This private feedback must never appear in the Wix-facing response.",
    status: "needs_review",
    venue: "johannesburg",
    verifiedGuest: true,
  },
  {
    featured: false,
    id: "3c153d53-33cc-4344-a2df-050ba3e84cb0",
    publicDisplayName: "Not Published",
    publicationConsent: true,
    publishedAt: "2026-09-26T15:00:00.000Z",
    rating: 2,
    reviewText: "This moderated review must not be visible in the public response.",
    status: "not_published",
    venue: "cape-town",
    verifiedGuest: true,
  },
];
